name: 'Auto Changelog PR'
description: 'Automatically updates CHANGELOG with PR number'
inputs:
  changelog-file:
    description: 'Changelog file name'
    required: true
    default: 'CHANGELOG.md'
  fail-on-needs-update: 
    description: 'Fails the action if there is no placeholder and the PR number is not present'
    required: true
    default: 'true'
  auto-commit: 
    description: 'Automatically commit the changes'
    required: true
    default: 'true'
outputs:
  did-update:
    description: 'Indicates if the changelog was updated with the PR number'
runs:
  using: 'node20'
  main: 'index.js'
